name: isca_soc2207_env
channels:
- conda-forge
dependencies:
- dask=2024.1.0
- ipykernel=6.29.0
- jinja2=3.1.3
- numpy=1.26.3
- pandas=2.2.0
- python=3.12.1
- pip=23.3.2
- pytest=7.4.4 
- sh=2.0.6
- tqdm=4.66.1
- xarray=2024.1.1
